### PR TITLE
[Fix] CMake Test fail.

### PR DESCRIPTION
**Pull request by soul12358**
First PR in my life XD.

### CODE REVIEW

**Review by angtsusiong — COMMENTED** [review]
LGTM

**Review by angtsusiong — APPROVED** [review]
GOOOOOO

**Review by angtsusiong — CHANGES_REQUESTED** [review]
Please add .keep to empty directories.

**Comment by YingChen-Lee** [comment]
I'll already tested it in my machine and everything works well!. Looks good to me.

**Review by YingChen-Lee — APPROVED** [review]
LGTM

**Comment by angtsusiong** [comment]
#4 也修好了
@soul12358 要大殺四方ㄌ
315545937_2258410564339788_8560187943339188132_n

**Review by angtsusiong — APPROVED** [review]

**Review by Ritabear — APPROVED** [review]
Good!

**Pull request merged**
